apiVersion: apps/v1
kind: Deployment

metadata:
 name: backend
 namespace: {{ .Values.namespace }}

spec:

 replicas: {{ .Values.backend.replicaCount }}

 selector:
   matchLabels:
     app: backend

 template:

   metadata:
     labels:
       app: backend

   spec:

     containers:

       - name: backend

         image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"

         imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

         ports:
           - containerPort: 8000

         env:
          - name: POSTGRES_HOST
            value: "postgres"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_DB
            valueFrom:
             secretKeyRef:
               name: postgres-secret
               key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
             secretKeyRef:
               name: postgres-secret
               key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
             secretKeyRef:
               name: postgres-secret
               key: POSTGRES_PASSWORD
