name: DevOps Capstone CI/CD

on:
 push:
   branches:
     - main

 workflow_dispatch:

permissions:
 id-token: write
 contents: read

env:
 AWS_REGION: ${{ vars.AWS_REGION }}
 EKS_CLUSTER_NAME: ${{ vars.EKS_CLUSTER_NAME }}
 ECR_BACKEND_REPOSITORY: ${{ vars.ECR_BACKEND_REPOSITORY }}
 ECR_FRONTEND_REPOSITORY: ${{ vars.ECR_FRONTEND_REPOSITORY }}

jobs:

 test:
   name: Test Application
   runs-on: ubuntu-latest

   steps:

     - name: Checkout code
       uses: actions/checkout@v4

     - name: Test backend
       run: |
         python -m pip install --upgrade pip
         pip install -r backend/requirements.txt

         python -m compileall backend


 deploy:
   name: Deploy to EKS
   needs: build-and-push
   runs-on: ubuntu-latest

   steps:

     - name: Checkout code
       uses: actions/checkout@v4

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v5
       with:
         role-to-assume: ${{ vars.AWS_ROLE_ARN }}
         aws-region: ${{ env.AWS_REGION }}

     - name: Get AWS account ID
       run: |
         echo "AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

     - name: Configure kubectl
       run: |
         aws eks update-kubeconfig \
           --region $AWS_REGION \
           --name $EKS_CLUSTER_NAME

     - name: Verify cluster
       run: |
         kubectl get nodes

     - name: Update backend image
       run: |
         kubectl set image deployment/backend \
           backend=AWSACCOUNTID.dkr.ecr.AWS_REGION.amazonaws.com/ECRBACKENDREPOSITORY:{GITHUB_SHA} \
           -n devops-capstone

